# Generated by Django 5.1.11 on 2025-07-10 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="skillset",
            name="skillset_id",
            field=models.PositiveIntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="topic",
            name="topic_id",
            field=models.PositiveIntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
