# Generated by Django 5.1.11 on 2025-07-11 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0003_seed_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="answer",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
